<?php

declare(strict_types=1);

namespace AlizHarb\LaravelHooks\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Symfony\Component\Finder\Finder;

class HookGenerateDocsCommand extends Command
{
    protected $signature = 'hook:generate-docs {--path=app : The directory to scan} {--output=HOOKS.md : The output file}';

    protected $description = 'Scan project for hook usage and generate documentation';

    public function handle(): int
    {
        $path = base_path($this->option('path'));
        $outputFile = base_path($this->option('output'));

        $this->info("Scanning [{$path}] for hook calls...");

        $finder = new Finder();
        $finder->files()->in($path)->name('*.php');

        $hooks = [];

        foreach ($finder as $file) {
            $content = $file->getContents();
            $relativePath = str_replace(base_path(), '', $file->getRealPath());

            // Regex for doAction, applyFilters and Blade directives
            preg_match_all('/(?:doAction|applyFilters|do_action|apply_filters)\s*\(\s*[\'"](.+?)[\'"]\s*(?:,|\))|@hook\s*\(\s*[\'"](.+?)[\'"]\s*(?:,|\))|@filter\s*\(\s*[\'"](.+?)[\'"]\s*(?:,|\))/is', $content, $matches);

            foreach ($matches[0] as $index => $fullMatch) {
                $hookName = $matches[1][$index] ?: ($matches[2][$index] ?: $matches[3][$index]);
                if (! $hookName) {
                    continue;
                }

                $type = str_contains(strtolower($fullMatch), 'filter') ? 'Filter' : 'Action';
                $hooks[$hookName][] = [
                    'type' => $type,
                    'file' => $relativePath,
                ];
            }
        }

        if (empty($hooks)) {
            $this->warn('No hooks found.');

            return self::SUCCESS;
        }

        ksort($hooks);

        $markdown = "# Available Hooks\n\n";
        $markdown .= "This file is automatically generated by `php artisan hook:generate-docs`.\n\n";
        $markdown .= "| Hook | Type | Location |\n";
        $markdown .= "| --- | --- | --- |\n";

        foreach ($hooks as $name => $occurrences) {
            foreach ($occurrences as $occ) {
                $markdown .= "| `{$name}` | {$occ['type']} | `{$occ['file']}` |\n";
            }
        }

        File::put($outputFile, $markdown);

        $this->info("Documentation generated: {$outputFile}");

        return self::SUCCESS;
    }
}
